# Generated by Django 4.2.4 on 2023-10-29 14:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0002_remove_order_product_order_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=0, default=0, max_digits=12, verbose_name="قیمت"
            ),
        ),
    ]
