# Generated by Django 4.2.4 on 2023-10-30 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0003_alter_product_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="order_full_price",
            field=models.PositiveBigIntegerField(
                default=0, verbose_name="قیمت کل سفارش"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="picture",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="upload/product/",
                verbose_name="عکس محصول",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=12, verbose_name="قیمت محصول"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="quantity",
            field=models.IntegerField(default=0, verbose_name="موجودی محصول"),
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_price",
                    models.PositiveBigIntegerField(verbose_name="قیمت محصول"),
                ),
                (
                    "product_discount",
                    models.PositiveBigIntegerField(
                        default=0, verbose_name="تخفیف محصول"
                    ),
                ),
                ("product_count", models.IntegerField(verbose_name="تعداد محصول")),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shop.order",
                        verbose_name="سفارش",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shop.product",
                        verbose_name="محصول",
                    ),
                ),
            ],
            options={
                "verbose_name": "آیتم",
                "verbose_name_plural": "آیتم\u200cها",
            },
        ),
    ]
