# Generated by Django 4.2.4 on 2023-10-29 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "picture",
                    models.ImageField(upload_to="upload/product/", verbose_name="عکس"),
                ),
                ("name", models.CharField(max_length=40, verbose_name="نام محصول")),
                ("quantity", models.IntegerField(default=1, verbose_name="تعداد")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=12, verbose_name="قیمت"
                    ),
                ),
            ],
            options={
                "verbose_name": "محصول",
                "verbose_name_plural": "محصولات",
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("1", "سبد خرید"),
                            ("2", "در انتظار پرداخت"),
                            ("3", "در انتظار تایید"),
                            ("4", "در حال ارسال"),
                            ("5", "تحویل شد"),
                            ("6", "انصراف داده شد"),
                        ],
                        max_length=1,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="shop.product"
                    ),
                ),
            ],
            options={
                "verbose_name": "سفارش",
                "verbose_name_plural": "سفارشات",
            },
        ),
    ]
